### ISSUE TITLE
🐛 Bug Report: Error code: Out of Memory

### ISSUE THREAD

**Issue by giffy994** [Simac-IT-NL/ms-dienst#10]
### 📜 Description

Het beginscherm van Backstage is niet beschikbaar

### 👍 Expected behavior

Het beginscherm van Backstage zou beschikbaar moeten zijn

### 👎 Actual Behavior with Screenshots

De browser (`/catalog?filters%5Bkind%5D=group&filters%5Buser%5D=all&limit=20`) toont de melding:

`Error code: Out of Memory`

Met een refresh knop.

<img width="1240" alt="image" src="https://github.com/user-attachments/assets/813efb2f-222a-4c72-b1d0-9a3e3a74c316">

### 👟 Reproduction steps

1. Login bij backstage
2. Klik rond in backstage
3. Ga terug naar de hoofdpagina

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by twanbeeren** [comment]
Komt dit probleem nog steeds voor? Backstage is bij mij wel bereikbaar en ik zie geen 50* Errors in de logs

**Comment by giffy994** [comment]
Lijkt te maken te hebben met Microsoft Edge op VDI die uit geheugen loopt.
