### ISSUE TITLE
Discussion:  Expected pipeline to run for deployment but it didn't

### ISSUE THREAD

**Issue by DaanCoolen** [Simac-IT-NL/ms-dienst#12]
### 📜 Description

Als we stap: 
"Production
To deploy your changes to Production, create a PR from develop -> main
After completing the PR, the new image version will be deployed to the production-cluster" 
zien we geen pipeline lopen. Wel komt er een prd omgeving bij. Maar in de readme wordt wel verwezen naar een pipeline. 
Zien wij iets verkeerd of...

### 👍 Expected behavior

Pipeline die gaat runnen na commit to main. 

### 👎 Actual Behavior with Screenshots

geen pipeline wel pod. 

### 👟 Reproduction steps

stap Production
To deploy your changes to Production, create a PR from develop -> main
After completing the PR, the new image version will be deployed to the production-cluster

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by twanbeeren** [comment]
Dit is hetzelfde principe als het issue [hier](https://github.com/Simac-IT-NL/ms-dienst/issues/5).

Wij gebruiken alleen pipelines voor het opzetten van de Git structuur. Dit gebeurd bijvoorbeeld als we een nieuwe applicatie toevoegen aan de applications-inventory.yaml

Daarna word de complete CD naar Kubernetes geregeld door ArgoCD via het GitOps principe. Hier worden geen pipelines voor gebruikt.

Voor meer info
https://codefresh.io/learn/argo-cd/

Vooral het zinnetje: "GitOps is a software engineering practice that uses a Git repository as its single source of truth. Teams commit declarative configurations into Git, and these configurations are used to create environments needed for the continuous delivery process"

Dit is een nieuwe manier van werken die voor jullie wat aanpassing vergt, maar jullie worden volledig ontzorgt in dit GitOps proces door deze dienst. Het staat op onze roadmap om het GitOps mechanisme (lees CD/deploy) wel te verduidelijken voor jullie, want ik kan mij voorstellen dat dit meermaals gevraagd zal worden in de toekomst

**Comment by twanbeeren** [comment]
Na overleg kwam naar voren dat de documentatie as if release 0.9 aangeeft dat er een pipeline moet runnen. Dit zal aangepast worden
