### ISSUE TITLE
🐛 Bug Report: Deployment van TAG 20241125.4 niet opgepakt

### ISSUE THREAD

**Issue by giffy994** [Simac-IT-NL/ms-dienst#3]
### 📜 Description

De Docker container is aangepast om een CURL commando uit te voeren (git hash `c28e0d1`). De build is van deze tag is succesvol uitgevoerd. Echter, de container met het PING command (vorige versie) blijft actief. Het is niet duidelijk of er een deployment van deze versie van de container is gestart.

### 👍 Expected behavior

Update pod met een container die CURL commando uitvoert op poort 80

### 👎 Actual Behavior with Screenshots

De oude versie van de container met daarin het PING commando blijft draaien

### 👟 Reproduction steps

1. Maak een nieuw project
2. Pas de docker container aan en uncomment de nginx applicatie
3. Pas de Dockerfile aan om PING te gebruiken
4. Pas het Dockerfile aan om CURL te gebruiken

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mpouleijn** [comment]
@giffy994 je zou eens de pod log kunnen bekijken via backstage om te zien of de applicatie wel is herstart. Als je in een pod alleen een curl uitvoerd on start zal deze pod blijven herstarten en de curl comando uit blijven voeren. Dit lijkt me geen gewenst gedrag.

**Comment by twanbeeren** [comment]
Daardoor werd de versie niet gebumpt. Dit is een gevolg van https://github.com/Simac-IT-NL/ms-dienst/issues/2
![image](https://github.com/user-attachments/assets/5c5d3039-c156-4ea0-a8d4-f317bb30070e)
De selfhosted agent (kaniko) kon geen cleanup uitvoeren van de files. 
`rm: cannot remove '/build-src/146348/.git/logs': Directory not empty`

Bij een re-run werkt het zoals het zou moeten en is de image ook aangepast:
![image](https://github.com/user-attachments/assets/76427ec1-2b85-4344-a2e5-f7971ddb6855)
![image](https://github.com/user-attachments/assets/7bbe9aec-1acc-4bb3-96e7-e531c44cef81)

Als het nog een keer voorkomt zal ik de kaniko logs bekijken waarom deze cleanup in de pipeline job fout gaat/ging. Het is niet mogelijk om de error op dit moment te reproduceren

**Comment by giffy994** [comment]
Dit gebeurt inderdaad vaker waardoor images niet worden geüpdate
