### ISSUE TITLE
🐛 Bug Report: Fix in documentatie lijkt geen oplossing (kubectl kan niet worden gebruikt)

### ISSUE THREAD

**Issue by giffy994** [Simac-IT-NL/ms-dienst#4]
### 📜 Description

Het is niet mogelijk om zoals in de documentatie staat vermeld een configmap aan te passen via kubectl 

![image](https://github.com/user-attachments/assets/b68bc0f8-48e4-4b0f-b5b8-af009a049c42)

### 👍 Expected behavior

Het zou mogelijk moeten zijn om zoals in de documentatie beschreven via kubectl de configmap configuratie te bekijken en eventueel aan te passen om het probleem op te lossen:

<img width="1676" alt="image" src="https://github.com/user-attachments/assets/9167e185-b2f8-4ac4-8466-b582b25aa47b">

### 👎 Actual Behavior with Screenshots

Het is niet mogelijk om zoals de documentatie suggereert via kubectl de configmap te bekijken of aan te passen.

### 👟 Reproduction steps

1. Deploy een pod met een ongeldige keyvault configuratie
2. Open de Deployment
3. Open de Pod
4. Open de Container
5. Scroll naar beneden naar de Errors sectie van de Pod
6. Klik op help
7. Volg de instructie om de configmap aan te passen conform de documentatie op [https://kubernetes.io](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/)

### 📃 Provide the context for the Bug.

Ik ben niet in staat om kubectl te gebruiken zoals beschreven op [https://kubernetes.io](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/) om troubleshooting uit te voeren.

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mpouleijn** [comment]
De config is alleen aan te passen via jullie git branch zoals beschreven in de handleiding van de dienst.

**Comment by giffy994** [comment]
Dat komt niet overeen met de documentatie in Backstage

**Comment by mpouleijn** [comment]
Ik refereerde naar een document wat wij met jullie gedeeld hebben met de volgende titiel "Work instruction for containerplatform with azure keyvault"
