### ISSUE TITLE
🐛 Bug Report: expexted after git commit of values.yml the pipeline should run

### ISSUE THREAD

**Issue by pdufourdela** [Simac-IT-NL/ms-dienst#5]
### 📜 Description

in my project pascaltryout1-1-project:
started with the default nginx
The pipeline runs -> Oke
pods fails -> secret "az-keyvault-creds" not found
I have removed unused env 
 see [git hash](79bba15de79bfeb67fcb737cd8af7476d7757e29) 

The pipeline did not start. 
run  it manual -> Nothing

### 👍 Expected behavior

The process should run the pipeline immediately and execute my changes

### 👎 Actual Behavior with Screenshots

nothing happens and I cannot see if something happend 
![BugAKS_Env](https://github.com/user-attachments/assets/8cdc4a35-9eef-40b0-9c4e-48b5b0448b90)

### 👟 Reproduction steps

in my project pascaltryout1-1-project:
started with the default nginx
The pipeline runs -> Oke
pods fails -> secret "az-keyvault-creds" not found
I have removed unused env 
 see [git hash](79bba15de79bfeb67fcb737cd8af7476d7757e29) 

The pipeline did not start. 
run  it manual -> Nothing

### 🖥️ Your Environment

DELA environment

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by mpouleijn** [comment]
Hi @pdufourdela, did you follow all steps in the manual? It looks like you mist a step i guess with the federated identity.

**Comment by pdufourdela** [comment]
The federated identity is after this point in the readme. If that is needed I suggest to reorder the steps.

**Comment by twanbeeren** [comment]
It's on our agenda to evaluate the way the Azure keyvault integration works and which order should be used for the steps

**Comment by twanbeeren** [comment]
Creation of the federated identity still will be a manual action untill there is an option to create these automatically.

And a pipeline will never run after changes to the values.yaml files. For release 0.9 I've added some documentation on how this works exactly.

In short there is a complete seperate mechanism that checks every 3 minutes if changes are made to the yaml files. This proces is hidden and you don't have to worry about this. However this isn't really clear from the README docs and this will be added for 0.9

Providing more deploying detailed information to engineers is a feature that is still under review. This enhancement should be a seperate issue.

**Comment by twanbeeren** [comment]
Release 0-9 is live
