### ISSUE TITLE
🐛 Bug Report: Container onbeschikbaar tijdens deployment

### ISSUE THREAD

**Issue by giffy994** [Simac-IT-NL/ms-dienst#7]
### 📜 Description

Tijdens het deployen van een nieuwe versie van de container wordt de container onbeschikbaar.

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/249edaa1-251b-484e-9407-f74d33e6864b">

### 👍 Expected behavior

De [default](https://medium.com/@chirag.dave/kubernetes-deployment-strategies-a-detailed-guide-61d7f0a11efe) update strategy is rolling update. Daarmee wordt onbeschikbaarheid van de container tijdens deployment geminimaliseerd en verstoringen voor eindgebruikers voorkomen.

### 👎 Actual Behavior with Screenshots

De container wordt onbeschikbaar tijdens de deployment. Hierdoor worden verstoringen ervaren door gebruikers tijdens deployment. Of, langdurige onbeschikbaarheid als er sprake is van een misconfiguratie.

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/8675ca55-de1a-4348-9654-0f24119ad3a8">

### 👟 Reproduction steps

1. Deploy een container
2. Update de Dockerfile en start een build pipeline
3. Wacht tot er een nieuwe versie van de container wordt opgestart

### 🖥️ Your Environment

YARN is niet geïnstalleerd op de VDI (enige manier om containerplatform te benaderen)

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by twanbeeren** [comment]
Hi Rino, 

Het is een optie in de values.yaml files om de updateStrategy aan te passen. Ik zie dat de default nu de standaard is en dat is idd Recreate.

In de controllers.main.stategy is er een optie om RollingUpdate te gebruiken. Ik verwacht dat dat zal werken zoals hier:

![image](https://github.com/user-attachments/assets/fe5511fd-08d0-463f-9574-9b5408dd5b84)

Dit is echter nog niet getest, en dat zullen we meenemen om dit te standaardiseren naar de toekomst

**Comment by twanbeeren** [comment]
Als dit is geimplementeerd en in productie draait zal ik het in deze issue aangeven. Voor nu zal ik hem sluiten

**Comment by giffy994** [comment]
1. Zou je de fix version aan kunnen geven voor dit issue?
2. Waar kan ik vinden welke opties ik allemaal in kan vullen voor deze configuratie?
