### ISSUE TITLE
🐛 Bug Report: Template without keyvault is still missing

### ISSUE THREAD

**Issue by pdufourdela** [Simac-IT-NL/ms-dienst#8]
### 📜 Description

for creating an pod without a keyfault the option to use it without a keyvault should be possilbe. 

### 👍 Expected behavior

to have an additional template to choose from to select without keyvault

### 👎 Actual Behavior with Screenshots

<img width="746" alt="Screenshot 2024-12-04 at 13 59 53" src="https://github.com/user-attachments/assets/cfdf43c9-eebc-4f1b-ade7-d1c26d45ff4e">

### 👟 Reproduction steps

login in backstage

template should be direct available

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

**Comment by twanbeeren** [comment]
Template without keyvault will be released with the next version. Changed this to an enhancement and will be released by 0.9

I'll leave this issue open till then

**Comment by twanbeeren** [comment]
Release 0-9 is live

**Comment by twanbeeren** [comment]
Release 0-9 is live
